spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1230
    url:  jdbc:mysql://localhost:3306/SpringCloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
env:
 dev24

