spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1230
    url: jdbc:mysql://localhost:3306/SpringCloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
